import { getCollection, type CollectionEntry } from 'astro:content';

export type Essay = CollectionEntry<'writing'>;

/**
 * Published essays, newest first. Drafts never escape this function, so
 * every surface (index, detail routes, RSS, sitemap) inherits one gate.
 */
export async function getPublishedWriting(): Promise<Essay[]> {
  const entries = await getCollection('writing', ({ data }) => data.draft === false);
  return entries.sort(
    (a, b) => b.data.pubDate.valueOf() - a.data.pubDate.valueOf(),
  );
}

/**
 * Reading time in whole minutes, floored at 1. 220 wpm is the common
 * long-form estimate; prose here is unhurried, so this reads slightly
 * conservative, which is the right direction to err.
 */
export function readingTime(body: string | undefined): number {
  const words = (body ?? '').trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 220));
}

/**
 * Long-form display date. Explicit UTC so the rendered string cannot drift
 * by a day with the build machine's timezone (the date suite locks this
 * class of bug elsewhere in the codebase).
 */
export function formatEssayDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/**
 * OG image for an essay. Reuses the photograph OG already generated by
 * scripts/build-og-images.mjs when the essay carries a hero; falls back to
 * the site card otherwise. A dedicated essay OG template is the documented
 * next upgrade (Writing_Surface_Plan_2026-05-30).
 */
export function essayOgImage(heroImage?: string): string {
  return heroImage ? `/og/photography/${heroImage}.jpg` : '/og/pages/home.jpg';
}
